### PR TITLE
Add solutions with Golang

### PR DESCRIPTION
**Pull request by nodauf**
Add Golang code for the exercises and their bonus.

### CODE REVIEW

**Comment by chvancooten** [comment]
This is great, thanks so much for this effort! I don't have much experience reading Go, but the code looks sane and is stylistically very similar to the other examples which is superb.

One question before I merge: I see you call your own repo as a dependency for the Windows API. What would be the common / most popular solution for this if this repo wasn't available? I'm trying to avoid the use of low-popularity imports (no offense 😁). If this is the cleanest solution however I'm absolutely fine with it.

Thanks again for your work!

**Comment by nodauf** [comment]
The best solution would be to use `golang.org/x/sys/windows` and implement the missing functions (copy / paste from my repo).

For **Bonus Exercice 3**, the solution would be to implement as follows (or generate the function with https://github.com/C-Sto/BananaPhone/tree/master/cmd/mkdirectwinsyscall, this is what I did):
```golang
alloc, err := bp.GetSysID("NtAllocateVirtualMemory")
...
bananaphone.Syscall(
		alloc, //ntallocatevirtualmemory
		thisThread,
		uintptr(unsafe.Pointer(&baseA)),
		0,
		uintptr(unsafe.Pointer(&regionsize)),
		uintptr(memCommit|memreserve),
		windows.PAGE_READWRITE,
	)
```

Definitely understand what you mean. Tell me if you prefer I update the code as above.

**Comment by chvancooten** [comment]
Thanks for clarifying! That makes complete sense. I would suggest making either of the following changes to ensure that the workshop examples give the full picture:

- Add a brief section to the README.md files on how to call the Windows API (as you did it in your repo) and how to use BananaPhone (+ references), so participants can learn about that process themselves

OR

- Merge the code where you import the APIs with the example snippets and add the explanation via comments

Do you agree? :)

**Comment by nodauf** [comment]
Yes, I will do it soon :)

**Comment by nodauf** [comment]
So I kept the code and updated the README to explain how to generate new Golang code when the Win32 API is not implemented in the official windows package.

I did the same for `BananaPhone` package, where I explained two ways to use the package. One by doing like the snippet code above, and the other way by using `mkdirectwinsyscall` to generate a function that will implement the call.

**Comment by chvancooten** [comment]
Hi @nodauf, sorry for the delay in looking at your PR - I was a bit preoccupied with the X33fcon conference :)
Thanks a bunch for adding these explanations. All looks good - will merge the PR now! I will refer to you for any support requests regarding Golang if you don't mind, since I definitely don't know all that much about it! Thanks again!

**Comment by nodauf** [comment]
No problem. I hope x33fcon was as good as it looked on Twitter ^^. Maye one day soon I will be able to go back to these conferences :crossed_fingers:

Sure, no problem for answering any questions regarding Golang :).

**Pull request merged**
